### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by rodovia** [Uriopass/Egregoria#103]
Trying to run the game from the master and from the lastest stable yields this:
```
[     1776 INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
[  1921339 INFO  wgpu_hal::gles::egl] Loading Wayland library to get the current display
[  1921729 INFO  wgpu_hal::gles::egl] Loading X11 library to get the current display
[  1947196 INFO  wgpu_hal::gles::egl] Using X11 platform
[  1986618 INFO  wgpu_hal::gles::egl] Display vendor "Mesa Project", version (1, 5)
[  1986711 INFO  wgpu_hal::gles::egl] 	EGL surface: +srgb
[  1986800 INFO  wgpu_hal::gles::egl] 	Trying native-render
[  1986907 INFO  wgpu_hal::gles::egl] 	EGL context: +robust access EXT
[  1990497 INFO  wgpu_hal::gles::egl] 	EGL context: +surfaceless
[  2265792 ERROR /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.16.0/src/vulkan/instance.rs:681] enumerate_adapters: Initialization of an object has failed
[  2322256 INFO  wgpu_hal::gles::adapter] Vendor: Intel
[  2322405 INFO  wgpu_hal::gles::adapter] Renderer: Mesa Intel(R) HD Graphics 2000 (SNB GT1)
[  2322444 INFO  wgpu_hal::gles::adapter] Version: OpenGL ES 3.0 Mesa 23.1.8-arch1.1
[  2322522 INFO  wgpu_hal::gles::adapter] SL version: OpenGL ES GLSL ES 3.00
[  2322680 INFO  wgpu_core::instance] Adapter Gl AdapterInfo { name: "Mesa Intel(R) HD Graphics 2000 (SNB GT1)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
[  2322855 ERROR /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.16.0/src/backend/direct.rs:594] Error in Adapter::request_device: Limit 'max_compute_workgroups_per_dimension' value 65535 is better than allowed 0
thread 'main' panicked at 'could not find device, have you installed necessary vulkan libraries?: RequestDeviceError': /home/runner/work/Egregoria/Egregoria/wgpu_engine/src/gfx.rs:192
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
      std::panicking::rust_panic_with_hook
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
   5: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   6: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   7: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   8: native_app::run::{{closure}}
   9: beul::execute
  10: native_app::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  14: main
  15: <unknown>
  16: __libc_start_main
  17: _start
```

**Comment by Uriopass** [comment]
Do you have a graphics card ? This seems like it is using the integrated intel gpu that was released 12 years ago. Which I don't support at the moment
