### ISSUE TITLE
Launching and crashing soon after

### ISSUE THREAD

**Issue by Arbee4ever** [Uriopass/Egregoria#109]
When I try to run the newest release on Fedora 39, it crashes after starting. When I run it using `./native_app` in the Terminal I get the error `Error trying to flush the wayland display: Broken pipe (os error 32)` once it crashes. The Client opens, but I can't interact with it, click anything in the game or move the Camera.

**Comment by Uriopass** [comment]
Wayland support is probably not great as I don't really tro to support it.  
Last time I tried using wayland every other program was broken too so I thought I'd wait until it matured a bit.

**Comment by Uriopass** [comment]
Can you try running master instead? I upgraded to winit 0.29 recently which could help.

**Comment by Arbee4ever** [comment]
Tried that, and it didt even launch and threw the error 
```
thread 'main' panicked at 'texture not found at path: assets/sprites/blue_noise_512.png (in dir: Ok("/home/arbee/Documents/Egregoria")): The image format could not be determined': /home/arbee/Documents/Egregoria/engine/src/texture.rs:353
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: engine::texture::TextureBuilder::from_path
   8: engine::framework::run::{{closure}}
   9: native_app::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
  14: __libc_start_call_main
  15: __libc_start_main_impl
  16: _start```
  even thought the texture at "assets/sprites/blue_noise_512.png" exists.

**Comment by Uriopass** [comment]
Hmmm now that's quite surprising, are you just doing cargo run ?

**Comment by Arbee4ever** [comment]
I did run `git lfs pull`

**Comment by Uriopass** [comment]
What does
`file assets/sprites/blue_noise_512.png`
Show ?

**Comment by Arbee4ever** [comment]
![blue_noise_512](https://github.com/Uriopass/Egregoria/assets/45911516/9b56a3aa-4563-4f6b-b3c2-2b9a63afbf06)
This

**Comment by Uriopass** [comment]
Hmmmm, can you run again ? I don't see why the image format would not be recognized

**Comment by Arbee4ever** [comment]
Oh.. Is that a Terminal Command? `assets/sprites/blue_noise_512.png: PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced` Didn't know that command existed

**Comment by Uriopass** [comment]
It is :) very useful

**Comment by Arbee4ever** [comment]
I deleted the file and reran `git lfs pull`, and it ran, but I couldn't interact with it again until it crashed with 
```
Io error: Broken pipe (os error 32)
thread 'main' panicked at 'Failed to run event loop: ExitFailure(1)': /home/arbee/Documents/Egregoria/engine/src/framework.rs:160
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: engine::framework::run::{{closure}}
   9: native_app::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
  14: __libc_start_call_main
  15: __libc_start_main_impl
  16: _start```
I'm guessing that is the same error as before?

**Comment by Uriopass** [comment]
I have never seen this error before. Are you running any "surprising" setup? Maybe an old computer, a networked disk, maybe you don't have a gpu?...

**Comment by Arbee4ever** [comment]
Nope... I don't think so...

**Comment by Arbee4ever** [comment]
Maybe it's the nvidia gpu messing stuff up... wouldn't be the first time

**Comment by Arbee4ever** [comment]
I reran it yet again and got the error: 
```
Io error: Connection reset by peer (os error 104)
Io error: Connection reset by peer (os error 104)
thread 'main' panicked at 'Failed to run event loop: ExitFailure(1)': /home/arbee/Documents/Egregoria/engine/src/framework.rs:160
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: engine::framework::run::{{closure}}
   9: native_app::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
  14: __libc_start_call_main
  15: __libc_start_main_impl
  16: _start

**Comment by Uriopass** [comment]
I'm thinking it might be related to the logging. Can you run

```rust
sed -i 's/release_max_level_info/release_max_level_off/g' native_app/Cargo.toml
```

then `cargo run --release` again?

**Comment by Uriopass** [comment]
But I'm mostly thinking it's wayland (which is networked) that's broken. In which case I can't investigate right now I need to setup a wayland desktop.

**Comment by Arbee4ever** [comment]
> I'm thinking it might be related to the logging. Can you run
> 
> ```rust
> sed -i 's/release_max_level_info/release_max_level_off/g' native_app/Cargo.toml
> ```
> 
> then `cargo run --release` again?

That crashed with `Io error: Broken pipe (os error 32)` before even showing any gui
I might be able to try it on Windows someday :D

**Comment by Uriopass** [comment]
Windows should definitely work. I run Ubuntu on X11 most days but I have a windows gaming pc where I try it occasionally and I haven't had any issues.

**Comment by Arbee4ever** [comment]
Yeah Windows can be more easily developed for because there isn't multiple display servers or something messing it up all the time

**Comment by Arbee4ever** [comment]
I just remembered I can just switch to xorg by just logging out setting it to xorg and logging back in... Now it works fine :D

**Comment by Uriopass** [comment]
Nice! So it was a Wayland issue. I'll try to reproduce it as it's slowly becoming the default.

**Comment by Uriopass** [comment]
As last time... Wayland+vulkan is buggy as hell with NVIDIA drivers. (Egregoria only supports vulkan on Linux as a graphics backend, I don't have time to make wgpu's opengl backend work)

When using the latest drivers I hit: https://github.com/gfx-rs/wgpu/issues/4775
And when using the stable drivers I hit https://github.com/NVIDIA/egl-wayland/issues/83#issuecomment-1773969793

:upside_down_face: 

Let's hope it gets better when the game is ready to be released! In the meantime, I can't test much.

**Comment by Uriopass** [comment]
Goods news. I'm pretty sure this is fixed by https://github.com/gfx-rs/wgpu/commit/e5c62fb5bd29c5bd99f2445e3b089689c0e145e2 which should come in the next wgpu release :)

**Comment by Uriopass** [comment]
Didn't made it in time for wgpu 0.19. It should be there in wgpu 0.20 though! (in a few months).

**Comment by Uriopass** [comment]
I think it's finally good! Can you try again?

**Comment by Arbee4ever** [comment]
Now I dont get a window at all and the logs don't tell me there's an issue, but when I run it from the terminal, I get `interface 'wl_surface' has no event 2` before any log output
[log_1720375223294615.log](https://github.com/user-attachments/files/16120221/log_1720375223294615.log)
![image](https://github.com/Uriopass/Egregoria/assets/45911516/d80990e1-3181-4177-b493-ac9c63ba8b35)
